<script setup lang="ts">
import { Sparkles } from "@lucide/vue";
const props = withDefaults(defineProps<{ active?: boolean; scope?: "page" | "section"; message?: string; longWaitMessage?: string; delay?: number; longWait?: number; layout?: "fill" | "viewport" }>(), { active: true, scope: "page", message: "正在排定乾坤、推演星曜，請稍候…", longWaitMessage: "仍在處理中，請再稍候片刻…", delay: 300, longWait: 8000, layout: "fill" });
const visible = ref(false);const waitingLong = ref(false);let delayTimer: ReturnType<typeof setTimeout> | undefined;let longTimer: ReturnType<typeof setTimeout> | undefined;
function clearTimers(){ if(delayTimer) clearTimeout(delayTimer);if(longTimer) clearTimeout(longTimer);delayTimer=undefined;longTimer=undefined; }
function start(){ clearTimers();visible.value=false;waitingLong.value=false;if(!props.active)return;delayTimer=setTimeout(()=>{visible.value=true},props.delay);longTimer=setTimeout(()=>{waitingLong.value=true},props.longWait); }
watch(() => [props.active, props.delay, props.longWait], start, { immediate: true });onBeforeUnmount(clearTimers);
</script>
<template>
  <div v-if="visible && active && scope === 'page'" class="app-loading app-loading--page" :class="`app-loading--${layout}`" role="status" aria-live="polite">
    <div class="app-loading__orbit"><i v-for="index in 4" :key="index" /><span><Sparkles :size="32" /></span></div><p>{{ waitingLong ? longWaitMessage : message }}</p>
  </div>
  <div v-else-if="visible && active" class="app-loading app-loading--section" role="progressbar" aria-label="載入中"><span /></div>
</template>
<style scoped>
.app-loading--page { display:flex;flex:1 1 auto;flex-direction:column;align-items:center;justify-content:center;width:100%;height:100%;min-height:0;padding:var(--space-6);text-align:center; }.app-loading--viewport { min-height:max(320px,calc(100dvh - var(--astrology-loader-viewport-offset,58px))); }.app-loading__orbit { position:relative;width:100px;height:100px;border:2px solid var(--color-border);border-radius:var(--radius-pill);animation:app-loading-orbit 10s linear infinite; }.app-loading__orbit>i { position:absolute;width:8px;height:8px;border-radius:var(--radius-pill);background:var(--color-brand-primary); }.app-loading__orbit>i:nth-child(1){left:44px;top:-5px}.app-loading__orbit>i:nth-child(2){right:-5px;top:44px}.app-loading__orbit>i:nth-child(3){left:44px;bottom:-5px}.app-loading__orbit>i:nth-child(4){left:-5px;top:44px}.app-loading__orbit>span { position:absolute;inset:15px;display:grid;place-items:center;border-radius:var(--radius-pill);background:var(--color-surface);color:var(--color-brand-primary);animation:app-loading-counter 10s linear infinite,app-loading-pulse 1.5s ease-in-out infinite alternate; }.app-loading--page p { max-width:320px;margin:27px 0 0;color:var(--color-text-primary);font-size:var(--font-size-body-sm);font-weight:var(--font-weight-medium);line-height:1.6; }.app-loading--section { width:min(calc(100% - 48px),620px);height:2px;margin:0 auto;overflow:hidden;background:var(--color-border); }.app-loading--section span { display:block;width:35%;height:100%;background:var(--color-brand-primary);transform:translateX(-100%);animation:app-loading-progress 1.15s linear infinite; }@keyframes app-loading-orbit{to{transform:rotate(360deg)}}@keyframes app-loading-counter{to{transform:rotate(-360deg)}}@keyframes app-loading-pulse{to{scale:1.12}}@keyframes app-loading-progress{to{transform:translateX(286%)}}@media(prefers-reduced-motion:reduce){.app-loading__orbit,.app-loading__orbit>span{animation-duration:20s}.app-loading__orbit>span{animation-name:app-loading-counter}.app-loading--section span{animation-duration:2.5s}}
</style>
