<script setup lang="ts">
import { AlertCircle, ArrowRight, CircleCheck, Info, TriangleAlert, X } from "@lucide/vue";
import { APP_SNACKBAR_EVENT, type AppSnackbarOptions } from "~/utils/app-snackbar";
type Kind = NonNullable<AppSnackbarOptions["type"]>;type Item = AppSnackbarOptions & { type: Kind };
const visible=ref(false);const current=ref<Item>({message:"",type:"info"});const queue:Item[]=[];let timer:ReturnType<typeof setTimeout>|undefined;let deadline=0;let remaining=0;
const defaults:Record<Kind,{title:string;duration:number}>={success:{title:"操作完成",duration:3000},info:{title:"提醒",duration:3000},warning:{title:"請留意",duration:5000},error:{title:"操作失敗",duration:5000}};
const icon=computed(()=>current.value.type==="success"?CircleCheck:current.value.type==="warning"?TriangleAlert:current.value.type==="error"?AlertCircle:Info);
function schedule(duration:number){remaining=duration;deadline=Date.now()+duration;timer=setTimeout(close,duration)}
function showNext(){if(visible.value||!queue.length)return;current.value=queue.shift()!;visible.value=true;schedule(current.value.duration??defaults[current.value.type].duration)}
function close(){if(timer)clearTimeout(timer);timer=undefined;visible.value=false;setTimeout(showNext,180)}
function pause(){if(!timer)return;clearTimeout(timer);timer=undefined;remaining=Math.max(0,deadline-Date.now())}
function resume(){if(visible.value&&!timer)schedule(remaining||500)}
function receive(event:Event){const detail=(event as CustomEvent<Partial<Item>>).detail;const type:Kind=["success","warning","error"].includes(detail?.type||"")?detail.type as Kind:"info";const next:Item={message:detail?.message?.trim()||"連線發生錯誤，請稍後再試。",type,title:detail?.title?.trim(),actionLabel:detail?.actionLabel?.trim(),actionTo:detail?.actionTo?.trim(),action:detail?.action,duration:detail?.duration};const last=queue.at(-1);if((last?.message===next.message&&last.type===next.type)||(visible.value&&current.value.message===next.message&&current.value.type===next.type))return;queue.push(next);showNext()}
async function followAction(){const item=current.value;close();if(item.action)await item.action();else if(item.actionTo)await navigateTo(item.actionTo)}
onMounted(()=>window.addEventListener(APP_SNACKBAR_EVENT,receive));onBeforeUnmount(()=>{window.removeEventListener(APP_SNACKBAR_EVENT,receive);if(timer)clearTimeout(timer)});
</script>
<template><Teleport to="body"><Transition name="fate-app-snackbar"><div v-if="visible" class="fate-app-snackbar" :class="`fate-app-snackbar--${current.type}`" :role="current.type==='error'||current.type==='warning'?'alert':'status'" :aria-live="current.type==='error'||current.type==='warning'?'assertive':'polite'" @mouseenter="pause" @mouseleave="resume" @focusin="pause" @focusout="resume" @touchstart="pause" @touchend="resume"><span class="fate-app-snackbar__icon"><component :is="icon" :size="20" /></span><div class="fate-app-snackbar__copy"><strong>{{ current.title || defaults[current.type].title }}</strong><span>{{ current.message }}</span><button v-if="current.actionLabel&&(current.actionTo||current.action)" class="fate-app-snackbar__action" type="button" @click="followAction">{{ current.actionLabel }} <ArrowRight :size="14" /></button></div><button class="fate-app-snackbar__close" type="button" aria-label="關閉提醒" @click="close"><X :size="18" /></button></div></Transition></Teleport></template>
<style scoped>
.fate-app-snackbar{position:fixed;z-index:var(--layer-snackbar);left:var(--fate-app-content-center-x,50vw);bottom:calc(var(--space-6) + env(safe-area-inset-bottom));display:grid;grid-template-columns:38px minmax(0,1fr) 44px;align-items:center;gap:var(--space-3);width:min(430px,calc(100vw - 28px));padding:var(--space-3);transform:translateX(-50%);border:1px solid var(--color-border);border-radius:var(--radius-xl);background:var(--color-surface-strong);box-shadow:var(--shadow-floating);color:var(--color-text-primary);backdrop-filter:blur(24px) saturate(150%)}.fate-app-snackbar__icon{display:grid;place-items:center;width:38px;height:38px;border-radius:var(--radius-md);background:var(--color-bg-subtle);color:var(--color-info)}.fate-app-snackbar--success .fate-app-snackbar__icon{color:var(--color-success)}.fate-app-snackbar--warning .fate-app-snackbar__icon{color:var(--color-warning)}.fate-app-snackbar--error .fate-app-snackbar__icon{color:var(--color-danger)}.fate-app-snackbar__copy{display:grid;gap:var(--space-1);min-width:0;text-align:left}.fate-app-snackbar__copy strong{font-size:var(--font-size-body-sm)}.fate-app-snackbar__copy>span{color:var(--color-text-secondary);font-size:var(--font-size-caption);line-height:1.5;overflow-wrap:anywhere}.fate-app-snackbar__action{display:inline-flex;align-items:center;justify-self:start;gap:var(--space-1);min-height:40px;margin-top:var(--space-1);padding:var(--space-2) var(--space-3);border:0;border-radius:var(--radius-sm);background:var(--color-bg-subtle);color:var(--color-text-primary);font-size:var(--font-size-body-sm);font-weight:var(--font-weight-bold)}.fate-app-snackbar__close{display:grid;place-items:center;width:44px;height:44px;border:0;border-radius:var(--radius-pill);background:transparent;color:var(--color-text-primary)}.fate-app-snackbar-enter-active,.fate-app-snackbar-leave-active{transition:opacity var(--motion-base) var(--ease-standard),transform var(--motion-base) var(--ease-standard)}.fate-app-snackbar-enter-from,.fate-app-snackbar-leave-to{opacity:0;transform:translateX(-50%) translateY(14px)}@media(max-width:760px){.fate-app-snackbar{bottom:calc(88px + env(safe-area-inset-bottom))}}@media(prefers-reduced-motion:reduce){.fate-app-snackbar-enter-active,.fate-app-snackbar-leave-active{transition:opacity var(--motion-fast) var(--ease-standard)}.fate-app-snackbar-enter-from,.fate-app-snackbar-leave-to{transform:translateX(-50%)}}
</style>
